=head1 NAME

aa-chroot - Execute command within given chroot jail

=head1 SYNOPSIS

B<aa-chroot> [B<-D>] [B<-O> I<FILE|FD>] I<NEWROOT> I<COMMAND> [I<ARG...>]

=head1 OPTIONS

=over

=item B<-D, --double-output>

Enable double-output mode. Instead of using stdout for regular output, and
stderr for warnings and errors, everything is sent both to stdout and stderr.
This is intended to redirect stderr to a log file, so full output can be both
shown on console and logged.

=item B<-h, --help>

Show help screen and exit.

=item B<-O, --log-file> I<FILE|FD>

Will duplicate all output (everything written to stdout or stderr) to the given
file or file descriptor. I<FILE|FD> can either be a (previously opened for
writing) file descriptor (must be > 2), or a file which will then be opened in
append mode.

=item B<-V, --version>

Show version information and exit.

=back

=head1 DESCRIPTION

B<aa-chroot>(1) sets the root filesytem for the current process to I<NEWROOT>,
which must exists, goes into this directory, chroots into it and chdir into the
(new) root ("/"). It then executes into I<COMMAND> (searched under the new root)
with the given I<ARG> (if any).

Note that B<aa-chroot>(1)'s parent process if unaffected by the change.
