=head1 NAME

aa-mvlog - Helper to move & rename log file

=head1 SYNOPSIS

B<aa-mvlog> [B<-D>] I<LOGFILE> I<DESTDIR>

=head1 OPTIONS

=over

=item B<-D, --double-output>

Enable double-output mode. Instead of using stdout for regular output, and
stderr for warnings and errors, everything is sent both to stdout and stderr.
This is intended to redirect stderr to a log file, so full output can be both
shown on console and logged.

=item B<-h, --help>

Show help screen and exit.

=item B<-V, --version>

Show version information and exit.

=back

=head1 DESCRIPTION

B<aa-mvlog>(1) is a small helper to move I<LOGFILE> into I<DESTDIR>, renaming it
to the TAI timestamp read from its first line (i.e. the first 25 bytes of
I<LOGFILE>), and creating in I<DESTDIR> a symlink named I<current> pointing to
it.

=head2 DEPRECATION WARNING

Please note that B<aa-mvlog>(1) has been deprecated and will be removed in the
next version of B<anopa>.
