=head1 NAME

aa-stage2 - Stage 2: Initialyzing system

=head1 SYNOPSIS

B<aa-stage2>

=head1 DESCRIPTION

B<aa-stage2>(1) is an B<execline> script called by B<aa-stage1> once the runtime
repository has been created and B<s6-svscan> is running as PID 1, to actually
perform all initialization tasks.

It will log messages into file I</var/log/boot/current>, prefixing them with a
TAI timestamp via B<s6-tai64n>.

It starts all services via B<aa-start>(1) using I</etc/anopa/listdirs/onboot> as
listdir, unless argument B<aa> was specified on kernel command line, in which
case I</etc/anopa/listdirs/ARGVALUE> is used as listdir intead.

If B<aa-start>(1) exits non-zero, it assumes there might not even be a getty
running, and will try to open a shell (I<sh -i>). Else, the system is assumed to
be ready.
