=head1 NAME

aa-tty - Prints the device name of the active tty

=head1 SYNOPSIS

B<aa-tty> [B<-D>]

=head1 OPTIONS

=over

=item B<-D, --double-output>

Enable double-output mode. Instead of using stdout for regular output, and
stderr for warnings and errors, everything is sent both to stdout and stderr.
This is intended to redirect stderr to a log file, so full output can be both
shown on console and logged.

=item B<-h, --help>

Show help screen and exit.

=item B<-V, --version>

Show version information and exit.

=back

=head1 DESCRIPTION

B<aa-tty>(1) is a small tool that will print to device name of the active tty.
It determines it by reading I<active> files in I</sys/class/tty> starting with
I</sys/class/tty/console/active> and "going up" as much as possible.
